idf_component_register(SRCS "main.cpp"
                              "cnc/espnow_manager.cpp" "cnc/cnc_manager.cpp"
                              "graphics/graphics_lgfx.cpp"
                              "graphics/graphics_primitive.cpp"
                              "graphics/graphics_helpers.cpp"
                              "graphics/image_manager.cpp"
                              "graphics/msgbox.cpp"
                              "scene/main_scene.cpp"
                              "scene/DRO_scene.cpp"
                              "scene/jog_scene.cpp"
                              "scene/turning_scene.cpp"
                              "scene/facing_scene.cpp"
                              "scene/parting_scene.cpp"
                              "scene/chamfer_billet_scene.cpp"
                              "scene/hemispherical_scene.cpp"
                              "scene/threading_scene.cpp"
                              "scene/keyway_scene.cpp"
                              "scene/spindle_position_scene.cpp"
                              "scene/realtime_command_scene.cpp"
                              "scene/global_settings_scene.cpp"
                              "scene/taper_morse_scene.cpp"
                              "scene/thread_iso_scene.cpp"
                              "scene/tool_manager_scene.cpp"
                              "scene/tool_database.cpp"
                              "scene/tool_catalog_scene.cpp"
                              "scene/probe_scene.cpp"
                              "gcode/GenerateGcode.cpp"
                              "gcode/GcodeMonitor.cpp"
                              "gcode/Tracking.cpp"
                              "i2c/i2c_scanner.cpp" "i2c/keypad.cpp" "i2c/ads1x15.cpp"
                              "brake/BrakeAlert.cpp"
                              "OTA/OTA_Manager.cpp"
                              "global_settings.cpp"
                              "global_vars.cpp"
                       INCLUDE_DIRS "." "cnc" "graphics" "i2c" "scene" "gcode" "brake" "OTA")